name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.19
        registry-url: https://registry.npmjs.org/
        cache: npm
        cache-dependency-path: '**/package.json'

    - name: Install dependencies
      run: |
        npm ci
      shell: bash
